// generated by sapper build at 2020-11-02T16:09:07.614Z
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
process.env.PORT = process.env.PORT || 3000;

console.log('Starting server on port ' + process.env.PORT);
require('./__sapper__/build/server/server.js');